### ISSUE TITLE
is there any way to scale down the hud? It is quite large

### ISSUE THREAD

**Issue by jrizzy93** [sinistersnare/CS-GO-Observer-Custom-HUD#3]
Hello, I am running a CSGO tournament, and came across this hud (which is amazing btw). But I don't know much about coding CSS, is there anyway to scale this down a little? Or did I miss something when installing? I tried going through the code, and nothing i tried worked. Any help would be great!
![68dab05a44946159f5b5a2b620979793](https://user-images.githubusercontent.com/34756071/39100793-2066e950-4655-11e8-9a29-25fd18b32c63.jpg)

**Comment by sinistersnare** [comment]
in `style.css`, the `#current_nick` rule sets the font size for the current spectated player. You can change that for smaller text. You can look around for `font-size` attributes if you think text is too big.

This HUD is kinda dead, ive been busy with life things, and I want to rewrite this in something better than html/css. Hope you can get some good mileage out of it!
