### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by MgWish** [sinistersnare/CS-GO-Observer-Custom-HUD#5]
Plz 
i request u Step by Step Video ty

**Comment by AlthalusAvan** [comment]
You have already been told it's not happening. It's noone's job to teach you how to use this. It's being provided for free, there are instructions in the Readme, figure it out from there. Stop opening issues on this.

**Comment by sinistersnare** [comment]
Thank you @AlthalusAvan.

@MgWish please refer to my previous comment on your last issue. Ask a programmer friend to help you if you want to learn how to use this. This project is dead to me, I dont want to work on it. If I get a bit more invested in CSGO this summer then I will make a new HUD, but I do not want to work on this any more. I hope that you understand that I do not work for other people for free, only for myself.
